# How to use PCMF package!

In [1]:
#import PCMF
from PCMF.Positive_CMF import Positive_Collective_Matrix_Factorization
#data processing
import numpy as np

# Make sample dataset(Example data set)

In [2]:
# Randomly generate the original matrix.
X  = np.random.random_sample((1000, 100))
Y = np.random.random_sample((1000, 30))
X, Y

(array([[0.24847769, 0.92837696, 0.30059839, ..., 0.12561425, 0.66277199,
         0.34027897],
        [0.22307267, 0.48443072, 0.57220612, ..., 0.49297108, 0.35689179,
         0.41624412],
        [0.7361003 , 0.77629826, 0.42066231, ..., 0.97781795, 0.84493988,
         0.35037373],
        ...,
        [0.12404128, 0.0019809 , 0.6390083 , ..., 0.94168058, 0.09853853,
         0.38612824],
        [0.07181645, 0.56613074, 0.60231026, ..., 0.55167077, 0.71364693,
         0.17202591],
        [0.88714109, 0.94597517, 0.09069533, ..., 0.71342583, 0.77460753,
         0.78309143]]),
 array([[0.46091998, 0.15893277, 0.50549811, ..., 0.24884235, 0.73122779,
         0.98397691],
        [0.02287738, 0.3495672 , 0.93856203, ..., 0.98989155, 0.66211367,
         0.92033014],
        [0.08953751, 0.20408854, 0.79054535, ..., 0.24215255, 0.74023685,
         0.32782198],
        ...,
        [0.1782251 , 0.08667535, 0.64887784, ..., 0.04384896, 0.65464416,
         0.27241068],
        [0.3

In [3]:
# Weight of each element of Y of loss function.
wY = np.random.random_sample((1000, 30))
wY

array([[0.59242526, 0.94391661, 0.81555406, ..., 0.45420413, 0.07689032,
        0.38228694],
       [0.10679816, 0.76132749, 0.8370853 , ..., 0.94615018, 0.65010113,
        0.51260314],
       [0.69759489, 0.28559725, 0.09380406, ..., 0.24183029, 0.55903652,
        0.55620306],
       ...,
       [0.84851777, 0.8064424 , 0.84641176, ..., 0.81146947, 0.67658812,
        0.29319071],
       [0.11170263, 0.76870714, 0.83241645, ..., 0.3189608 , 0.04840133,
        0.86164286],
       [0.07015802, 0.31711469, 0.2241136 , ..., 0.92555989, 0.00483782,
        0.80231256]])

# Training PCMF

In [4]:
cmf = Positive_Collective_Matrix_Factorization(X, Y, alpha=0.5, d_hidden=12, lamda=0.1)

In [5]:
cmf.train(link_X = 'sigmoid', link_Y = 'sigmoid', 
          weight_X = None, weight_Y =wY, 
          optim_steps=501, verbose=50, lr=0.05)

[Info] At time-step 0, loss is 17.701169967651367
[Info] At time-step 50, loss is 9.045083999633789
[Info] At time-step 100, loss is 5.19536828994751
[Info] At time-step 150, loss is 3.2300522327423096
[Info] At time-step 200, loss is 1.722853183746338
[Info] At time-step 250, loss is 1.0922274589538574
[Info] At time-step 300, loss is 1.0090701580047607
[Info] At time-step 350, loss is 0.9783576130867004
[Info] At time-step 400, loss is 0.9572911858558655
[Info] At time-step 450, loss is 0.9419869184494019
[Info] At time-step 500, loss is 0.9304507374763489


(array([[0.00619301, 0.00809157, 0.00185326, ..., 0.00295491, 0.00102456,
         0.00220665],
        [0.00611927, 0.007062  , 0.00174178, ..., 0.00672322, 0.00129402,
         0.00208969],
        [0.00177775, 0.00116573, 0.00310689, ..., 0.00278253, 0.00548184,
         0.00568578],
        ...,
        [0.00470339, 0.00284737, 0.00219152, ..., 0.00136558, 0.00203684,
         0.00263309],
        [0.00225398, 0.00183056, 0.00184434, ..., 0.00957577, 0.00270244,
         0.00212347],
        [0.00132301, 0.00318799, 0.00137424, ..., 0.00370901, 0.00549211,
         0.00241262]], dtype=float32),
 array([[0.00328673, 0.00322875, 0.00319095, ..., 0.00300826, 0.00441328,
         0.00408365],
        [0.00308168, 0.00410404, 0.00410875, ..., 0.00431702, 0.00392337,
         0.00203434],
        [0.00486501, 0.00450918, 0.00258157, ..., 0.00380386, 0.00226068,
         0.00241681],
        ...,
        [0.00401949, 0.00417189, 0.00420266, ..., 0.00427896, 0.00387536,
         0.0037397 